apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubeapi-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubeapi-deployment
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubeapp-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubeapp-deployment
  targetCPUUtilizationPercentage: 50