apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-deployment  
  labels:
    app: kubeapp
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1
  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app: kubeapp
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: kubeapp
    spec:
      containers:
        - name: kubeapp
      # THIS CHANGE IS MUST FOR AKS-------------------
          image: rrkubeacr.azurecr.io/kubeclient:v1
      # ---------------------------------------
          resources:
            requests:
              cpu:  400m
              memory: 200Mi
            limits:           
              cpu:  500m    
              memory: 200Mi            
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
      # THIS CHANGE IS MUST FOR AKS -------------------    
            - name: KubeApiurl
              value: http://kubeapi-service

      imagePullSecrets:
        - name: acr-secret
      # ---------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: kubeapp-service
spec:
  type: LoadBalancer # CHANGE TO LOADBALANCER FOR THIS SERVICE TO BE ACCESSED FROM EXTERNAL 
  selector:
    app: kubeapp
  ports:
    - port: 80 # CHANGE TO DEFAULT PORT
      #targetPort: 80
      #nodePort: 32000 // NOT REQUIRED
      protocol: TCP
